fivedays_3hours_forcast_api: "https://api.openweathermap.org/data/2.5/forecast?"
sixteendays_daily_forcast_api: "https://api.openweathermap.org/data/2.5/forecast/daily?"
api_key: "2c07c4b723a79973f52a9f847a271f34"
api_key_16days: "ec68f9bd86f9edd4506ca35c8210b490"
lang: "ja"
maximum_time_delta: 15
closet_recommend: {
  temp_1: {
    recommend: "東京の真冬と同じ服装。<br>長袖カットソー+カーディガン（またはニット1枚）+コート、靴はスニーカーやパンプスなどがGOOD。ストールがあると便利です。重ね着をして調節できるようにしましょう。",
    min: -10,
    max: 8
  },
  temp_2: {
    recommend: "東京の冬と同じ服装。長袖カットソー+カーディガン（またはニット1枚）+コート、靴はスニーカーやパンプスなどがGOOD。ストールがあると便利です。重ね着をして調節できるようにしましょう。",
    min: 8,
    max: 15
  },
  temp_3: {
    recommend: "東京の冬の初めと同じ服装。薄手の長袖+カーディガン（またはニット1枚）+裏地のあるトレンチコート、靴はスニーカーやパンプスなどがGOOD。ストールがあると便利です。重ね着をして調節できるようにしましょう。",
    min: 15,
    max: 18
  },
  temp_4: {
    recommend: "東京の秋と同じ服装。薄手の長袖+カーディガン+寒がりの方は薄手の上着、靴はスニーカーやパンフスなどがGOOD。薄手のストールがあると便利です。重ね着をして調節できるようにしましょう。",
    min: 18,
    max: 22
  },
  temp_5: {
    recommend: "東京の春と同じ服装。<br>半袖+カーディガン、靴はスニーカーやパンプスなどがGOOD。薄手のストールがあると便利です、重ね着をして調節できるようにしましょう。",
    min: 22,
    max: 26
  },
  temp_6: {
    recommend: "東京の夏の初めと同じ服装。半袖+薄手のカーディガン、靴はサンダルがGOOD。レストランなど冷房が効いている場所があります。羽織りものや薄手のストールで調節できるようにしましょう。",
    min: 26,
    max: 30
  },
  temp_7: {
    recommend: "東京の夏と同じ服装。半袖に靴はサンダルがGOOD。レストランなど冷房が効いている場所があります。薄手の羽織りものやストールで調節できるようにしましょう。熱中症対策に帽子などの日除けグッズもあると便利です。",
    min: 30,
    max: 34
  },
  temp_8: {
    recommend: "東京の夏と同じ服装。半袖に靴はサンダルがGOOD。レストランなど冷房が効いている場所があります。薄手の羽織りものやストールで調節できるようにしましょう。熱中症対策に帽子などの日除けグッズもあると便利です。",
    min: 34,
    max: 100
  },
}
get_temp_time: {
  morning: "00:00:00",
  afternoon: "06:00:00",
  night: "12:00:00",
}
list_city: {
  hanoi: {
    city_code: hanoi,
    country_code: vn,
    city_name: "Hà Nội",
    id: 0,
    weather_description: [
      "ハノイには四季があり、この時期の気候は冬です。曇りの日が多く、気温が15℃を下回る日もあります。防寒対策が必要となります。", # 1月
      "ハノイには四季があり、この時期の気候は冬です。曇りの日が多く、気温が15℃を下回る日もあります。防寒対策が必要となります。", # 2月
      "ハノイには四季があり、この時期の気候は春です。気温が15～25℃ほどと、日によって気温差が大きい時期です。", # 3月
      "ハノイには四季があり、この時期の気候は夏です。朝晩にスコールが降ることがあります。最高気温が30℃を超える日が多く、湿度も高いです。熱中症に気を付けましょう。", # 4月
      "ハノイには四季があり、この時期の気候は夏です。朝晩にスコールが降ることがあります。最高気温が30℃を超える日が多く、湿度も高いです。熱中症に気を付けましょう。", # 5月
      "ハノイには四季があり、この時期の気候は夏です。朝晩にスコールが降ることがあります。最高気温が30℃を超える日が多く、湿度も高いです。熱中症に気を付けましょう。", # 6月
      "ハノイには四季があり、この時期の気候は夏です。朝晩にスコールが降ることがあります。最高気温が30℃を超える日が多く、湿度も高いです。熱中症に気を付けましょう。", # 7月
      "ハノイには四季があり、この時期の気候は夏です。朝晩にスコールが降ることがあります。最高気温が30℃を超える日が多く、湿度も高いです。熱中症に気を付けましょう。", # 8月
      "ハノイには四季があり、この時期の気候は夏です。朝晩にスコールが降ることがあります。最高気温が30℃を超える日が多く、湿度も高いです。熱中症に気を付けましょう。", # 9月
      "ハノイには四季があり、この時期の気候は夏です。朝晩にスコールが降ることがあります。最高気温が30℃を超える日が多く、湿度も高いです。熱中症に気を付けましょう。", # 10月
      "ハノイには四季があり、この時期の気候は秋です。気温が15～25℃ほどと、日によって気温差が大きい時期です。", # 11月
      "ハノイには四季があり、この時期の気候は冬です。曇りの日が多く、気温が15℃を下回る日もあります。防寒対策が必要となります。" # 12月
      
    ]
  },
  danang: {
    city_code: danang,
    country_code: vn,
    city_name: "Đà Nẵng",
    id: 1,
    weather_description: [
      "平均気温が20℃前後ですが、雨が多く、肌寒く感じる時期です。海は波が高くなるので注意が必要です。晴れた日はプールサイドで日光浴が楽しめます。", # 1月
      "平均気温は23℃前後で、雨も少なくなる時期です。雨の日や朝晩は冷え込むことが多く、上着は必要です。海は波が高いので注意が必要です。", # 2月
      "平均気温は25℃前後で、雨はほとんど降りません。雨の日や朝晩は冷え込むことが多く、上着は必要です。プールを楽しめる日も増えてきます。", # 3月
      "最高気温が30℃を超え、晴れる日が多い時期です。日除け対策・水分補給をしっかりして、熱中症に気を付けましょう。", # 4月
      "最高気温が30℃を超え、晴れる日が多い時期です。日除け対策・水分補給をしっかりして、熱中症に気を付けましょう。", # 5月
      "最高気温が30℃を超え、晴れる日が多い時期です。日除け対策・水分補給をしっかりして、熱中症に気を付けましょう。", # 6月 
      "最高気温が30℃を超え、晴れる日が多い時期です。日除け対策・水分補給をしっかりして、熱中症に気を付けましょう。", # 7月
      "最高気温が30℃を超え、晴れる日が多い時期です。日除け対策・水分補給をしっかりして、熱中症に気を付けましょう。", # 8月
      "最高気温が30℃を超え、晴れる日が多い時期です。日除け対策・水分補給をしっかりして、熱中症に気を付けましょう。", # 9月
      "平均気温は25℃前後と過ごしやすいですが、台風が多く湿度が高い時期です。晴れた日はプールに入れますが、少し肌寒く、海は波が高いので注意が必要です。", # 10月
      "平均気温は25℃前後と過ごしやすいですが、台風が多く湿度が高い時期です。晴れた日はプールに入れますが、少し肌寒く、海は波が高いので注意が必要です。", # 11月
      "平均気温が20℃前後と比較的過ごしやすい時期です。晴れた日はプールに入れますが、少し肌寒く、海は波が高いので注意が必要です。朝晩にスコールが降ることがあります。" # 12月
    ]
  },
  # hochiminh: {
  #   city_code: Thanh pho Ho Chi Minh,
  #   country_code: vn,
  #   city_name: "",
  #   id: 2
  # },
  # bangkok: {
  #   city_code: bangkok,
  #   country_code: th,
  #   id: 3
  # },
  # seoul: {
  #   city_code: seoul,
  #   country_code: kr,
  #   id: 4
  # }
}
data_file_path: "./cities_weather_data.json"
# list_weather_condition: ['Thunderstorm', 'Drizzle', ]
weather_conditions: [
  {
    type: 'Thunderstorm',
    images: 'static/images/lightning_rain.jpeg',
    japanese: '雷雨'
  },
  {
    type: 'Drizzle',
    images: 'static/images/rain3.jpeg',
    japanese: '霧雨'
  },
  {
    type: 'Rain',
    images: 'static/images/rain.jpeg',
    japanese: '雨'
  },
  {
    type: 'Snow',
    images: 'static/images/snow.jpeg',
    japanese: '雪'
  },
  {
    type: 'Atmosphere',
    images: 'static/images/mist.jpeg',
    japanese: '霧'
  },
  {
    type: 'Clear',
    images: 'static/images/sunny.jpeg',
    japanese: '晴れ'
  },
  {
    type: 'Clouds',
    images: 'static/images/cloud.jpeg',
    japanese: '曇り'
  },
]